export { default as Layout } from "./layout"
export { default as Seo } from "./seo"
export { default as Menu } from "./menu"
export { default as Hero } from "./hero"
export { default as About } from "./about"